### ISSUE TITLE
Suggestion for changing banner

### ISSUE THREAD

**Issue by kevnroberts** [kevnroberts/tomhagerman#22]
You could maybe alter the banner to something like this:

``` html
<div class="Banner">
  <h1>Tom Hagerman</h1>
</div>
```

and the css:

``` css
.Banner {
    background-image: url(b.png);
    width: 100%;
    height: 10rem;
    background-size: 100%;
    border: 1px solid transparent;
    color: #c28954;
}
.Banner h1 {
    margin-top: .75em;
    letter-spacing: .5em;
}
```
